from models import Store

def main():
    storeOfBikes = Store('A Loja', 'Rua 1')
    storeOfBikes.addBike('Vermelho')
    storeOfBikes.addBike('Vermelho')
    storeOfBikes.addBike('Vermelho')
    storeOfBikes.addBike('Vermelho')
    storeOfBikes.addBike('Vermelho')
    storeOfBikes.addBike('Branco')
    storeOfBikes.addBike('Branco')
    storeOfBikes.addBike('Branco')
    storeOfBikes.addBike('Branco')
    storeOfBikes.addBike('Branco')
    storeOfBikes.addClient('Nome1', 'email1@mail.com', '11122233344')
    storeOfBikes.addClient('Nome2', 'email2@mail.com', '12345678901')
    # storeOfBikes.addClient('Nome3', 'email3@mail.com', '13345678901')
    storeOfBikes.addClient('Nome3', 'email3@mail.com', '13345678901')
    # storeOfBikes.addRental('dailyd', 'email2@mail.com', 1)
    # storeOfBikes.addRental('weekly', 'email4@mail.com', 1)
    storeOfBikes.addRental('weekly', 'email3@mail.com', 1)
    storeOfBikes.addRental('weekly', 'email3@mail.com', 1)
    storeOfBikes.addRental('weekly', 'email2@mail.com', 3, True)
    storeOfBikes.addRental('weekly', 'email3@mail.com', 1)
    storeOfBikes.showBikes()
    # print(storeOfBikes.bikes)
    # print(storeOfBikes.rents)
    # print(storeOfBikes.clients)
    # storeOfBikes.calculateRental('email1@mail.com')
    # storeOfBikes.calculateRental('email2@mail.com')
    storeOfBikes.calculateRental('email3@mail.com')
    storeOfBikes.showBikes()

main()